version: "3.8"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,cloudformation,lambda,route53,iam
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    ports:
      - "4566:4566"
    volumes:
      - "./localstack-data:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"